#!/usr/bin/env bash

set -e

cat wrap_begin.html

markdown_py \
  -q \
  -x plantuml_markdown \
  -x mdx_partial_gfm 2> >(grep -v '^Successful' >&2) \
  | hxpipe \
    | sed -r 's/^Ahref CDATA ([^h][^t][^t][^p].*|.{1,3})\.md$/Ahref CDATA \1.html/g' \
    | sed -r 's/^Ahref CDATA ([^h][^t][^t][^p].*|.{1,3})\.markdown$/Ahref CDATA \1.html/g' \
  | hxunpipe

cat wrap_end.html
